=== Afroditi-Tavanioti/LondonAttractions/LondonAttractions_new2.dtd
<!ELEMENT London_Sightseeing (Title, Special_Offers*, LondonAttractions+, must_sees?)>
<!ELEMENT Title (#PCDATA)>

<!-- Special Offers -->
<!ELEMENT Special_Offers (Offer*)>
<!ELEMENT Offer (Special_Offer, Offer_including)>
<!ATTLIST Offer 
    id ID #REQUIRED
       name CDATA #REQUIRED>

<!ELEMENT Special_Offer (Adult, child)>
<!ATTLIST Special_Offer 
    id ID #REQUIRED
    days (1 | 2 | 3 | 4 | 5 | 6 | 7 | 10) #REQUIRED>

<!ELEMENT Adult EMPTY>
<!ATTLIST Adult 
    unit_price CDATA #REQUIRED
    price CDATA #REQUIRED>

<!ELEMENT child EMPTY>
<!ATTLIST child 
    unit_price CDATA #REQUIRED
    price CDATA #REQUIRED
    age CDATA #FIXED "5-15">

<!ELEMENT Offer_including (including_o+)>
<!ELEMENT including_o (#PCDATA)>
<!ATTLIST including_o 
    id ID #IMPLIED>

<!-- London Attractions -->
<!ELEMENT LondonAttractions (Attraction+)>

<!ELEMENT Attraction (URL, small_description, Attraction_title, extra_attraction_info, doing, includings?,Facts?, Reservations?, Knowing_before?, Note?, Address, operating?, Notice?, For_more?, FAQS?, getting_there?, family_friendly?, environment, category?, Votes, image)>
<!ATTLIST Attraction 
    id_Attr ID #REQUIRED
    booking (required | not_required) "not_required"
    normal_value CDATA #IMPLIED
    unit_value CDATA #FIXED "£"
    in_offer IDREFS #IMPLIED>

<!ELEMENT URL (#PCDATA)>
<!ELEMENT small_description (#PCDATA)>
<!ELEMENT Attraction_title (#PCDATA)>
<!ELEMENT extra_attraction_info (spending_time)>
<!ELEMENT spending_time (#PCDATA)>

<!ELEMENT doing (value_d, Highlights?, Facts?)>
<!ATTLIST doing 
    title CDATA #FIXED "What you'll do">
<!ELEMENT value_d (#PCDATA)>
<!ELEMENT Highlights (Highlight*)>
<!ELEMENT Highlight (#PCDATA)>

<!ELEMENT Facts (Fact*)>
<!ELEMENT Fact (#PCDATA)>

<!ELEMENT includings (including+)>
<!ATTLIST includings 
    title CDATA #FIXED "What's included">
<!ELEMENT including (#PCDATA | Not_in)*>

<!ELEMENT Not_in (#PCDATA)>


<!ELEMENT Reservations (value?, procedure?, booking_notes?)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT procedure (step+, value?)>
<!ELEMENT step (#PCDATA)>

<!ELEMENT booking_notes (#PCDATA)>

<!ELEMENT Note (#PCDATA)>
<!ATTLIST Note
    title CDATA #FIXED "Please Note">

<!ELEMENT Knowing_before ((Facilities | Getting_in | Busy_tip | note | Disclaimer | Accessibility)*)>

<!ATTLIST Knowing_before 
    title CDATA #FIXED "Know before you go">
	
<!ELEMENT Facilities (#PCDATA)>
<!ELEMENT Getting_in (#PCDATA)>
<!ELEMENT Busy_tip (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT Disclaimer (#PCDATA)>
<!ELEMENT Accessibility (#PCDATA)>

<!ELEMENT Address (#PCDATA)>
<!ATTLIST Address 
    title CDATA #FIXED "Where you'll be">
	

<!ELEMENT operating (Monday?, Tuesday?, Wednesday?, Thursday?, Friday?, Saturday?, Sunday?, openings?, special_closings*, closing?)>

<!ELEMENT Monday (Timing*)>
<!ATTLIST Monday dayid ID #REQUIRED>

<!ELEMENT Tuesday (Timing*)>
<!ATTLIST Tuesday dayid ID #REQUIRED>

<!ELEMENT Wednesday (Timing*)>
<!ATTLIST Wednesday dayid ID #REQUIRED>

<!ELEMENT Thursday (Timing*)>
<!ATTLIST Thursday dayid ID #REQUIRED>

<!ELEMENT Friday (Timing*)>
<!ATTLIST Friday dayid ID #REQUIRED>

<!ELEMENT Saturday (Timing*)>
<!ATTLIST Saturday dayid ID #REQUIRED>

<!ELEMENT Sunday (Timing*)>
<!ATTLIST Sunday dayid ID #REQUIRED>

<!ELEMENT Timing (#PCDATA)>

<!ELEMENT openings (opening*)>
<!ATTLIST openings
    variable_dates CDATA #IMPLIED
    for CDATA #IMPLIED
    days IDREFS #IMPLIED
>
<!ELEMENT opening (#PCDATA)>
<!ATTLIST opening
    for CDATA #IMPLIED
>
	
<!ELEMENT closing (days?, match_days*)>

<!ATTLIST closing     
    specific_dates CDATA #IMPLIED
    days CDATA #IMPLIED>
	
<!ELEMENT special_closings (date*)>

<!ELEMENT date EMPTY>
<!ATTLIST date 
    value CDATA #REQUIRED
    note CDATA #IMPLIED>

	
	
<!ELEMENT match_days (#PCDATA)>
<!ELEMENT days (#PCDATA)>
<!ATTLIST days 
    dayid IDREFS #REQUIRED>

<!ELEMENT Notice (#PCDATA)>
<!ELEMENT For_more (#PCDATA)>
<!ATTLIST For_more 
    title CDATA #FIXED "Find out More">

<!-- FAQs -->
<!ELEMENT FAQS (FAQ*)>
<!ELEMENT FAQ (question, answer)>
<!ELEMENT question (#PCDATA)>
<!ELEMENT answer (#PCDATA)>

<!-- Getting There -->
<!ELEMENT getting_there (Buses?, Train?, Other?)>
<!ATTLIST getting_there 
    title CDATA #FIXED "How to get there">
<!ELEMENT Buses (#PCDATA)>
<!ELEMENT Train (#PCDATA)>
<!ELEMENT Other (#PCDATA)>

<!-- Νέα στοιχεία/ιδιότητες -->
<!ELEMENT family_friendly (#PCDATA)> <!-- 0–3 -->
<!ELEMENT environment (#PCDATA)>
<!ELEMENT category (#PCDATA)> <!-- Μπορεί να επαναλαμβάνεται -->

<!ELEMENT Votes (Vote*)>
<!ELEMENT Vote (username, stars, comment?)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT stars (#PCDATA)> <!-- 1–5 -->
<!ELEMENT comment (#PCDATA)>

<!ELEMENT image (#PCDATA)> <!-- URL ή οντότητα -->

<!-- Must-Sees -->
<!ELEMENT must_sees EMPTY>
<!ATTLIST must_sees 
    ids IDREFS #REQUIRED>

=== Afroditi-Tavanioti/LondonAttractions/LondonAttractions_new2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE London_Sightseeing SYSTEM "LondonAttractions_new2.dtd">


<London_Sightseeing>

   <Title>THE LONDON PASS</Title>
   

   <Special_Offers>
		<Offer id="of1" name="The London Pass"><!--The best way to explore the majority of London's sights-->
 
			<Special_Offer id="sp1" days="3">
				<Adult unit_price="129" price="387" />
				<child unit_price="64" price="128" age="5-15" />
			</Special_Offer>
		 
			<Offer_including>
				<including_o id="in1_of1">Free cancellation within 30 days</including_o>
				<including_o id="in2_of1">Choose the attractions you want to see and visit them over 3 days</including_o>
				<including_o id="in3_of1">Valid for 3 calendar days from first use</including_o>
				<including_o id="in4_of1">Our handy app itinerary helps you plan the perfect trip</including_o>
				<including_o id="in5_of1">There's no need to pick before you purchase. Just choose attractions as you go!</including_o>
				<including_o id="in6_of1">If you don't save on your sightseeing, we'll refund you the difference!</including_o>
				<including_o id="in7_of1">No need for multiple tickets - just scan the Go City app at each attraction</including_o>
			</Offer_including>
		</Offer>
	 
	 
		<Offer id="of2" name="The London Pass Plus"><!--The complete London experience: access all our attractions plus four premium must-sees-->
	 
			<Special_Offer id="sp2" days="1">
				<Adult unit_price="109" price="109" />
				<child unit_price="79" price="158" age="5-15" />
			</Special_Offer>
	 
			<Offer_including>
				<including_o id="in1_of2">Free cancellation within 30 days</including_o>
				<including_o id="in2_of2">Choose the attractions you want to see and visit them over a single day</including_o>
				<including_o id="in3_of2">Valid for 1 calendar day from first use</including_o>
				<including_o id="in4_of2">Our handy app itinerary helps you plan the perfect trip</including_o>
				<including_o id="in5_of2">There's no need to pick before you purchase. Just choose attractions as you go!</including_o>
				<including_o id="in6_of2">If you don't save on your sightseeing, we'll refund you the difference!</including_o>
				<including_o id="in7_of2">No need for multiple tickets - just scan the Go City app at each attraction</including_o>
			</Offer_including>
 
		</Offer>
   
	</Special_Offers>



	<LondonAttractions>
		<Attraction id_Attr="id_at1" booking="required" normal_value="38.00" unit_value="£" in_offer="of2">
			<URL>https://londonpass.com/en/london-attractions/view-from-the-shard</URL>
			<small_description>Discover an architectural marvel and a symbol of modern London.</small_description>
			<Attraction_title>The View from The Shard</Attraction_title>
			
			<extra_attraction_info>
			   <spending_time>Up to an hour (&lt;1hr)</spending_time>
            </extra_attraction_info>

			<doing title="What you'll do">
				<value_d>
					From a 1970s office block to one of the world’s most distinguished buildings, ascend to London’s highest viewpoint at The View from The Shard.
					Journey to a height of up to 800ft (244m), to the top of London’s tallest observation platform and premium visitor attraction, The View from The Shard.
					Formerly known as the London Bridge Tower, 'The Shard' was designed by famed architect, Renzo Piano.
					Piano, who is most famous for designing the Pompidou Centre in Paris, France, began designing The Shard in 2000.
					His design was fuelled by the desire to create a modern building that stood out amongst the London Skyline without appearing too overbearing.
					As such, the building resembles a large piece of glass pointing out of the ground, and thus, The Shard was aptly named.
					Piano’s design has become a symbol of modern architecture in contemporary London.
					It incorporates both aesthetically and structurally unique features, drawing inspiration from the spires of different London churches.
					The building’s windows have a special glaze that reacts to light in a very intuitive way.
					Depending on the season or time of day, the glass can reflect different intensities of light, casting unique luminosity.
					The entire building process took over three years to complete.
					In that time, the structure rose by 10 feet per day.
					Many of the glass panels were put in place before the building reached its terminal height of 1000 feet.
					By 2012, it officially became the tallest building in Europe.
					The Shard offers a multitude of corporate, entertainment and dining facilities.
					Floors 2 to 28 of the building are used as office space rental areas.
					The 31st to 33rd floors are dedicated to restaurants.
					The five-star hotel, Shangri-La takes up a staggering 18 levels, from the 34th floor to the 52nd Floor.
					Some even call The Shard their home, as floors 53 to 65 are occupied by residential apartments.
					The best viewing spot in The Shard is, of course, its pinnacle.
					Enjoy unparalleled views over London from the building’s multi-floor observatory on the 68th to 72nd floors.
				</value_d>
			</doing>

			<includings title="What's included">
				<including>
					Your pass includes entry to the indoor viewing platform on the 68th and 69th floor, the open-air Skydeck on the 72nd floor and a digital photo package, comprising four photos.
				</including>
				<including>
					Once you’ve had your pass scanned, you’ll receive an exclusive £5 per person retail credit voucher for use in the on-site gift shop (subject to a minimum spend of £20 per person).
				</including>
			</includings>

			<Reservations>
				<value>You must pre-book your time slot online before visiting. Tickets can only be booked online.</value>
				<procedure>
					<step>(1) Follow this link to the specific The London Pass booking page on The View from The Shard’s website. You will be unable to book using your pass via the main website.</step>
					<step>(2) Select the number of tickets you require. Remember, each person in your group must have their own pass.</step>
					<step>(3) Select your visit date and a timeslot for entry. Your pass must be valid on your chosen visit date.</step>
					<step>(4) Enter your pass numbers, separated with commas and then enter the promo code: GOCITY23</step>
					<step>(5) Finally, enter your details so your entry voucher can be emailed to you.</step>
				</procedure>
			</Reservations>

			<Knowing_before title="Know before you go">
				<Getting_in>
					Simply show your pass and booked timeslot entry voucher at the main admissions desk and you’re good to go!
				</Getting_in>
			</Knowing_before>

			<Address title="Where you'll be">Railway Approach, London, GB</Address>

			<operating>
				<Monday dayid="a1_d1"/>
				<Tuesday dayid="a1_d2"/>
				<Wednesday dayid="a1_d3">
					<Timing>11AM–6PM</Timing>
				</Wednesday>
				<Thursday dayid="a1_d4">
					<Timing>11AM–6PM</Timing>
				</Thursday>
				<Friday dayid="a1_d5">
					<Timing>11AM–6PM</Timing>
				</Friday>
				<Saturday dayid="a1_d6">
					<Timing>10AM–9PM</Timing>
				</Saturday>
				<Sunday dayid="a1_d7">
					<Timing>11AM–6PM</Timing>
				</Sunday>
				<openings>
					<!-- Αν χρειάζεται, αναφορά σε working day ids -->
				</openings>
				<closing>
					<days dayid="a1_d1 a1_d2" />
				</closing>
			</operating>
			
			<family_friendly>3</family_friendly>
			<environment>indoors</environment>
			<category>Modern and Urban</category>
			<Votes>
			  <Vote>
				<username>traveler1</username>
				<stars>5</stars>
				<comment>Great experience.</comment>
			  </Vote>
			</Votes>
			<image>https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/The_Shard_from_the_Sky_Garden_2015.jpg/1200px-The_Shard_from_the_Sky_Garden_2015.jpg</image>
			
		</Attraction>
		
		
		<Attraction id_Attr="id_at2" normal_value="42.00" unit_value="£" in_offer="of2">
			<URL>https://londonpass.com/en/london-attractions/london-eye</URL>
		
			<small_description>
				Discover an architectural marvel and a symbol of modern London.
			</small_description>
		
			<Attraction_title>The London Eye</Attraction_title>
		
			<extra_attraction_info>
			   <spending_time>Up to an hour (&lt;1hr)</spending_time>
            </extra_attraction_info>
		
			<doing title="What you'll do">
				<value_d>
				    Are you looking to take your London experience to new heights? Take a ride on Europe’s tallest cantilevered observation wheel in the heart of the city – a must-do on your London vacation.
				    Originally constructed as a temporary exhibit to celebrate the new millennium, the London Eye offers panoramic views of the city’s skyline that stretches as far as 25 miles on a clear day. That’s to Windsor Castle!
				    Standing at an impressive 135 metres (443ft) high, the London Eye boasts 32 glass pods that represent each one of London’s boroughs. Step into the spacious capsule, that’s completely enclosed and climate-controlled, and be transported to the heights of the city.
				    Spot the grandeur of Buckingham Palace, the clock tower housing Big Ben, and the gothic structures of the Houses of Parliament. Gaze out at other famous silhouettes such as the Shard, the winding River Thames, and the majestic dome of St. Paul’s Cathedral. These sights become even more magical at sunset or when night falls, and the city lights begin to twinkle.
				</value_d>
			</doing>
		
			<includings title="What's included">
				<including>
					Your pass gives you access to a flight on The London Eye. Soaring 135 metres above the city, the observation wheel offers an unrivaled aerial tour of the historic skyline.
				</including>
			</includings>
		
			<Reservations>
				<value>
				   You can book your spot up to 15 days in advance on the Go City Reservations Portal. You’ll need your order/pass number(s) and the email you used to purchase.
				   Please note!
