=== Afroditi-Tavanioti/LondonAttractions/rental.dtd
<!ELEMENT rentalCompany (carList, offerList)>
<!ATTLIST rentalCompany
    name CDATA #REQUIRED
    rating CDATA #REQUIRED>
	
<!ELEMENT carList (car+)>
<!ELEMENT car (carModel, capacity, featureList, priceList)>
<!ATTLIST car id ID #REQUIRED>
	
<!ELEMENT carModel (#PCDATA)>
<!ATTLIST carModel
    transmission (automatic | manual) "automatic"
    fuel (petrol | diesel | electric) "petrol">
	
<!ELEMENT capacity (#PCDATA)>

<!ELEMENT featureList (feature*)>
<!ELEMENT feature (#PCDATA)>
<!ATTLIST feature
    extra_charge (yes | no) "no">

<!ELEMENT priceList (price+)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price
    period (weekdays | weekends | holidays) #REQUIRED>

<!ELEMENT offerList (offer*)>
<!ELEMENT offer (validity)>
<!ATTLIST offer
    carIDs CDATA #REQUIRED
    discount CDATA #REQUIRED>

<!ELEMENT validity (from, to)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>

=== Afroditi-Tavanioti/LondonAttractions/rentalCompanyInvalid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rentalCompany SYSTEM "rental.dtd">
<rentalCompany name="AutoRentals"> <!--Λείπει το rating το οποίο είναι υποχρεωτικό -->
    <carList>
        <car id="C3">
            <carModel transmission="manual" fuel="diesel">Sedan X</carModel>
            <capacity>4</capacity>
            <featureList>
                <feature>GPS</feature>
            </featureList>
            <priceList>
                <price period="weekends">40.00</price>
            </priceList>
        </car>
    </carList>

    <offerList>
        <offer carIDs="C3" discount="10%">
            <validity>
                <from>2025-07-01</from>
                <!-- Λείπει το στοιχείο <to> το οποίο είναι υποχρεωτικό -->
            </validity>
        </offer>
    </offerList>
</rentalCompany>

=== Afroditi-Tavanioti/LondonAttractions/rentalCompany.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rentalCompany SYSTEM "rental.dtd">
<rentalCompany name="AutoRentals" rating="4.5">
    <carList>
        <car id="C1">
            <carModel transmission="manual" fuel="diesel">Sedan X</carModel>
            <capacity>5</capacity>
            <featureList>
                <feature>GPS</feature>
                <feature extra_charge="yes">air conditioning</feature>
            </featureList>
            <priceList>
                <price period="weekdays">50</price>
                <price period="weekends">60</price>
            </priceList>
        </car>
        <car id="C2">
            <carModel transmission="automatic" fuel="diesel">SUV Y</carModel>
            <capacity>4</capacity>
            <featureList>
                <feature>air conditioning</feature>
            </featureList>
            <priceList>
                <price period="weekdays">40</price>
                <price period="weekends">55</price>
                <price period="holidays">70</price>
            </priceList>
        </car>
    </carList>
    <offerList>
        <offer carIDs="C1 C2" discount="10%">
            <validity>
                <from>2025-05-01</from>
                <to>2025-05-30</to>
            </validity>
        </offer>
    </offerList>
</rentalCompany>
